name: meta-t-s

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: yarn dev --host
  # database:
  #   build:
  #     context: ./database
  #     dockerfile: Dockerfile
  #   # environment:
  #   #   POSTGRES_USER: postgres
  #   #   POSTGRES_PASSWORD: postgres
  #   #   POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./database/data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: /app/backend
