name: meta-t-s

services:
  # frontend:
  #   container_name: meta-t-s-frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: yarn dev --host
  database:
    container_name: meta-t-s-database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
  backend:
    container_name: meta-t-s-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/mydb
    ports:
      - "9797:9797"
    command: /app/backend
