/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/ListBanner.vue')['default']
    CryptoLists: typeof import('./components/CryptoLists.vue')['default']
    CryptoSymbols: typeof import('./components/CryptoSymbols.vue')['default']
    MainPage: typeof import('./components/MainPage.vue')['default']
    Metaheuristics: typeof import('./components/Metaheuristics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tasks: typeof import('./components/Tasks.vue')['default']
  }
}
